### ISSUE TITLE
2020_07_22

### ISSUE THREAD

**Issue by JungJaeLee-JJ** [hoon4233/2020-summer-Algo-study#1]
@JungJaeLee-JJ 
[10774 저지](https://www.acmicpc.net/problem/10774)
[1922 네트워크 연결](https://www.acmicpc.net/problem/1922)

@hoon4233 
[2458 키 순서](https://www.acmicpc.net/problem/2458)
[6593 상범빌딩](https://www.acmicpc.net/problem/6593)

@sgu0927 
[2352 반도체 설계](https://www.acmicpc.net/problem/2352)
[2529 부등호](https://www.acmicpc.net/problem/2529)

**Comment by sgu0927** [comment]
@JungJaeLee-JJ
10774 저지 - greedy 알고리즘을 통해 풀어보았다. 
1922 네트워크 연결 - Kruskal 알고리즘을 통해 최소 spanning tree를 만드는 문제였다.

@hoon4233
2458 키 순서 - 플로이드 와샬 알고리즘을 확실히 이해할 수 있었다.
6593 상범빌딩 - 3차원 BFS를 해결하지 못했다. 다음번엔 꼭 풀 수 있을 것이다.

@sgu0927
2352 반도체 설계 - LIS에 대해서 다시 한번 생각하게 되는 문제였다
2529 부등호 - 위상정렬의 Indegree 로 푸는 방법, dfs로 푸는 방법 두 가지의 차이점과 방법에 대해 알 수 있었다.

**Comment by hoon4233** [comment]
@JungJaeLee-JJ
10774 저지 - disjoint set으로 분류된 문제지만 greedy스럽게 풀었다. 방대한 양의 input을 받는 greedy 문제에 대한 해결방법도 생각해보았다.
1922 네트워크 연결 - kruskal 알고리즘에 대해 배우는 좋은 계기가 되었다. kruskal 알고리즘을 최적화 하는 방법에 대해서도 논의하였다.

@hoon4233
2458 키 순서 - floyd warshall 알고리즘에 대해 배우는 좋은 계기가 되었다. 정재의 코드를 보며 모든 거리를 기록하는게 아닌 True, False로만 기록하는 방법에 대해서도 생각해보았다.
6593 상범빌딩 - 처음 접해본 3차원 문제여서 당황했지만 2차원 bfs를 확장하기만 하면 되는 문제였다.

@sgu0927
2352 반도체 설계 - 재귀를 이용해 작성하였지만 시간초과가 나서 아쉬웠다. 친구들의 코드를 보고 LIS 문제였다는 것을 깨달았고 LIS문제에 대해 더 공부해야겠다고 생각하였다.
2529 부등호 - 역시 재귀를 이용해 작성해보려 했지만 실패했다. 위상정렬 문제임을 깨달았고 위상정렬에 대해 더 공부해야겠다고 생각했다.

**Comment by JungJaeLee-JJ** [comment]
@JungJaeLee-JJ
10774 저지 - disjointset인데 그리디 알고리즘으로 해결할수있었다.
1922 네트워크 연결 - 전형적인 크루스칼 알고리즘 문제였고, union find로 집합을 나누고, 연결된 edge의 수가 n-1 이 되었을 때(다 연결되었을 때) 종료하였다. 

@hoon4233
2458 키 순서 - 플로이드와샬문제를 많이 풀어봤지만 처음보는 유형이였다. 플로이드와샬 3중 for문 안에서 i,j,k순서를 바꾸면 틀렸는데, 왜 틀리는지는 아직까지 구상하지 못하였다.
6593 상범빌딩 - DFS로 풀려고 하였으나, 완전 탐색문제가 아닌, 최소거리 탐색문제였기 때문에 시간초과가 났다. BFS로 3차원을 도는 간단한 문제였다.

@sgu0927
2352 반도체 설계 - LIS알고리즘 유형을 많이 봤지만, 처음 보는 유형이였고 많은 고민을 하였다. 그러나 실제 구현은 간단하였다.
2529 부등호 - 위상정렬의 2가지 방법을 알게되었다. (DFS,indegree)
